#!/bin/bash

mkdir BAMs
cd BAMs

# Use the following line to run this script:
# curl  http://www.elegansvariation.org/data/download/download_bams.sh | bash
#
# Requirements:
#    wget --no-check-certificate is required for downloading files.
#    We recommend using Homebrew (brew.sh) for Unix/Mac OS or Cygwin (cygwin.com) on windows.
#

wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/AB1.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/AB1.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/BRC20067.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/BRC20067.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/BRC20263.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/BRC20263.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/CB4851.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/CB4851.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/CB4852.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/CB4852.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/CB4853.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/CB4853.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/CB4854.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/CB4854.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/CB4855.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/CB4855.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/CB4856.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/CB4856.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/CB4857.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/CB4857.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/CB4858.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/CB4858.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/CB4932.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/CB4932.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/CX11254.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/CX11254.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/CX11262.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/CX11262.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/CX11264.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/CX11264.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/CX11271.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/CX11271.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/CX11276.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/CX11276.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/CX11285.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/CX11285.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/CX11292.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/CX11292.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/CX11307.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/CX11307.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/CX11314.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/CX11314.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/CX11315.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/CX11315.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/DL200.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/DL200.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/DL226.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/DL226.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/DL238.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/DL238.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA189.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA189.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA191.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA191.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA252.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA252.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA348.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA348.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA349.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA349.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA36.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA36.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA363.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA363.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA369.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA369.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA372.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA372.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA396.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA396.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ED3005.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ED3005.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ED3011.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ED3011.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ED3012.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ED3012.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ED3017.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ED3017.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ED3040.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ED3040.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ED3046.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ED3046.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ED3048.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ED3048.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ED3049.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ED3049.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ED3052.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ED3052.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ED3073.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ED3073.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ED3077.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ED3077.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/EG4347.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/EG4347.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/EG4349.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/EG4349.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/EG4724.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/EG4724.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/EG4725.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/EG4725.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/EG4946.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/EG4946.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/GXW1.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/GXW1.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JT11398.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JT11398.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU1088.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU1088.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU1172.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU1172.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU1200.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU1200.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU1212.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU1212.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU1213.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU1213.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU1242.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU1242.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU1246.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU1246.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU1249.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU1249.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU1395.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU1395.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU1400.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU1400.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU1409.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU1409.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU1440.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU1440.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU1491.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU1491.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU1530.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU1530.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU1543.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU1543.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU1568.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU1568.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU1580.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU1580.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU1581.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU1581.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU1586.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU1586.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU1652.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU1652.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU1666.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU1666.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU1792.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU1792.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU1793.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU1793.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU1808.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU1808.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU1896.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU1896.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU1934.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU1934.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2001.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2001.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2007.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2007.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2016.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2016.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2017.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2017.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2106.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2106.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2131.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2131.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2141.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2141.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2234.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2234.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2250.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2250.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2257.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2257.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2316.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2316.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2464.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2464.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2466.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2466.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2478.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2478.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2513.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2513.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2519.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2519.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2522.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2522.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2526.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2526.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2534.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2534.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2565.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2565.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2566.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2566.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2570.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2570.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2572.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2572.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2575.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2575.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2576.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2576.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2578.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2578.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU258.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU258.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2581.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2581.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2586.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2586.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2587.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2587.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2592.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2592.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2593.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2593.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2600.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2600.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2610.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2610.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2619.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2619.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2800.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2800.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2811.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2811.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2825.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2825.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2829.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2829.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2838.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2838.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2841.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2841.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2853.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2853.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2862.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2862.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2866.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2866.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2878.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2878.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2879.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2879.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2906.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2906.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2907.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU2907.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU310.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU310.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU311.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU311.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU3125.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU3125.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU3127.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU3127.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU3128.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU3128.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU3132.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU3132.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU3134.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU3134.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU3135.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU3135.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU3137.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU3137.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU3140.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU3140.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU3144.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU3144.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU323.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU323.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU346.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU346.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU360.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU360.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU367.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU367.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU393.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU393.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU394.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU394.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU397.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU397.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU406.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU406.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU440.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU440.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU561.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU561.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU642.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU642.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU751.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU751.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU774.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU774.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU775.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU775.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU778.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU778.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU782.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU782.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU792.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU792.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU830.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU830.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU847.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU847.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/KR314.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/KR314.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/LKC34.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/LKC34.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/LSJ1.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/LSJ1.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/MY1.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/MY1.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/MY10.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/MY10.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/MY16.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/MY16.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/MY18.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/MY18.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/MY2147.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/MY2147.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/MY2212.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/MY2212.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/MY23.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/MY23.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/MY2453.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/MY2453.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/MY2530.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/MY2530.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/MY2535.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/MY2535.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/MY2573.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/MY2573.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/MY2585.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/MY2585.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/MY2693.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/MY2693.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/MY2713.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/MY2713.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/MY2741.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/MY2741.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/MY518.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/MY518.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/MY679.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/MY679.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/MY772.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/MY772.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/MY795.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/MY795.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/MY920.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/MY920.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/N2.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/N2.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC1.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC1.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC1049.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC1049.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC1107.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC1107.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC166.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC166.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC195.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC195.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC199.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC199.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC2.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC2.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC207.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC207.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC231.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC231.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC236.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC236.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC242.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC242.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC251.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC251.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC252.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC252.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC255.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC255.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC256.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC256.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC258.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC258.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC259.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC259.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC260.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC260.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC261.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC261.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC262.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC262.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC265.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC265.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC266.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC266.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC267.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC267.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC268.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC268.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC269.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC269.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC271.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC271.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC272.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC272.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC274.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC274.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC275.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC275.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC276.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC276.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC277.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC277.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC3.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC3.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC501.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC501.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC511.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC511.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC513.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC513.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC514.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC514.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC515.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC515.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC522.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC522.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC523.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC523.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC526.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC526.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC527.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC527.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC528.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC528.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC529.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/NIC529.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/PB303.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/PB303.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/PB306.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/PB306.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/PS2025.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/PS2025.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/PX179.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/PX179.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QG2075.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QG2075.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QG536.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QG536.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QG556.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QG556.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QG557.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QG557.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QW947.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QW947.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QX1211.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QX1211.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QX1212.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QX1212.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QX1233.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QX1233.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QX1791.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QX1791.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QX1792.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QX1792.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QX1793.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QX1793.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QX1794.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QX1794.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/RC301.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/RC301.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/WN2001.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/WN2001.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/WN2002.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/WN2002.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/WN2033.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/WN2033.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/WN2050.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/WN2050.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/XZ1513.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/XZ1513.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/XZ1514.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/XZ1514.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/XZ1515.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/XZ1515.bam.bai
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/XZ1516.bam
wget --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/XZ1516.bam.bai

#########################
##### new 77 isotypes ###
#########################

wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA347.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA347.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA592.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA592.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA593.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA593.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA594.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA594.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA640.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA640.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA701.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA701.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA703.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA703.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA705.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA705.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA706.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA706.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA710.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA710.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA712.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA712.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA722.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA722.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA723.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA723.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA724.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA724.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA730.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA730.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA732.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA732.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA733.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA733.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA738.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA738.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA740.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA740.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA741.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA741.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA742.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA742.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA743.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA743.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA744.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA744.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA745.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA745.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA746.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA746.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA760.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA760.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA768.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA768.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA777.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA777.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA778.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA778.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA807.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA807.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA812.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA812.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA923.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA923.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA928.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA928.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA930.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/ECA930.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU3141.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU3141.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU3166.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU3166.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU3167.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU3167.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU3169.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU3169.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU3224.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU3224.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU3225.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU3225.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU3226.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU3226.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU3228.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU3228.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU3280.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU3280.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU3282.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU3282.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU3291.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/JU3291.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QG2811.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QG2811.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QG2813.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QG2813.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QG2818.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QG2818.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QG2823.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QG2823.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QG2824.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QG2824.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QG2825.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QG2825.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QG2827.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QG2827.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QG2828.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QG2828.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QG2832.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QG2832.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QG2835.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QG2835.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QG2836.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QG2836.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QG2837.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QG2837.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QG2838.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QG2838.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QG2841.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QG2841.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QG2843.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QG2843.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QG2846.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QG2846.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QG2850.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QG2850.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QG2854.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QG2854.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QG2855.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QG2855.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QG2857.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QG2857.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QG2873.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QG2873.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QG2874.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QG2874.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QG2875.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QG2875.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QG2877.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QG2877.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QG2932.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/QG2932.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/XZ1672.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/XZ1672.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/XZ1734.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/XZ1734.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/XZ1735.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/XZ1735.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/XZ1756.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/XZ1756.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/XZ2018.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/XZ2018.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/XZ2019.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/XZ2019.bam.bai
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/XZ2020.bam
wget  --no-check-certificate https://elegansvariation.org.s3.amazonaws.com/bam/XZ2020.bam.bai
